args = {
    "data": {
        "dataset": "worldtrace",
        "train_path": "data/train_subset.pkl",
        "val_path": "data/train_subset.pkl",
        "traj_length": 200,
        "num_workers": 8,
        "mask_ratio": 0.5,
        "task_mode": "mixed",
        "completion_prob": 0.7,
        "predict_len": 8,
    },
    "model": {
        "name": "single_stage_flow_matching",
        "hidden_size": 256,
        "depth": 6,
        "num_heads": 4,
        "mlp_ratio": 4.0,
        "use_moe": True,
        "num_experts": 4,
        "top_k": 2,
        "use_spectral_loss": True,
        "spectral_loss_weight": 0.1,
        "sample_steps": 16,
        "adaptive_patch": {
            "enabled": True,
            "score_mode": "rule",
            "hidden_dim": 64,
            "threshold_global": 0.55,
            "threshold_relative": 0.10,
            "min_patch_len": 4,
            "max_patch_len": 24,
            "smooth_kernel": 5,
            "learned_weight": 0.5,
            "patch_encoder_dim": 256,
            "patch_encoder_heads": 4,
            "patch_encoder_layers": 2,
            "patch_dropout": 0.1,
            "use_patch_length_embedding": True,
            "use_point_patch_fusion": True,
            "fusion_heads": 4,
            "fusion_dropout": 0.1,
            "detach_patch_scores": False,
        },
    },
    "training": {
        "batch_size": 256,
        "n_epochs": 100,
        "lr": 1e-4,
        "weight_decay": 1e-4,
        "patience": 20,
        "lr_patience": 3,
        "lr_decay_factor": 0.5,
        "grad_clip": 1.0,
        "seed": 42,
        "device": "auto",
    },
}
